sekolah/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls'))
]

web/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path('', views.home, name='home'),
    path('all/', views.allschool, name='allschool'),
]

web/models.py
from django.db import models

class School(models.Model):
    name = models.CharField(max_length=100)
    address = models.TextField(max_length=250)
    url = models.URLField(max_length=250, blank=True)
    image = models.ImageField(upload_to='web/images/')
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

web/views.py
from django.shortcuts import render
from .models import School

# Create your views here.

def home(request):
    schools = School.objects.all()
    return render(request, 'web/home.html', { 'schools' : schools })

def allschool(request):
    schools = School.objects.all()
    return render(request, 'web/allschool.html', { 'schools' : schools })

web/templates/web/allschool.html
{% extends 'web/base.html' %}

{% block content %}

    <div class='container'>
    {% for school in schools %}
        <h2>{{ school.name }}</h2>
        <p>
        <img src="{{ school.image.url }}" alt="{{ school.name }} picture" width="100" height="50"> <br>
        {{ school.address }} <br>
        {% if school.url %}
        <a href="{{ school.url }}" target="_blank">Website</a> <br>
        {% endif %}
        </p>
    {% endfor %}
    </div>
    
{% endblock %}

web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&&family=Pacifico&display=swap" rel="stylesheet">

    {% load static %}

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- Feather Icons -->
   <script src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"></script>
    
   <!-- Custom CSS -->
   <link rel="stylesheet" href="{% static 'web/custom.css' %}">
    

    <title>Sekolahtopia</title>
</head>
<body>

  <header class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-custom">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Sekolahtopia</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                <a id="menubar" class="nav-link" href="{% url 'web:home' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a id="menubar" class="nav-link" href="#">Database</a>
                </li>
                <li class="nav-item">
                  <a id="menubar" class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                  <a id="menubar" class="nav-link" href="#">Blog</a>
                </li>
              </ul>
          </div>
        </div>
    </nav>
  </header>

   <!-- Start Template Block -->
   <div class="container">
     {% block content %}
     {% endblock %}
   </div>

   
    <!-- Optional Bootstrap JavaScript -->
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>         

   <footer class="footer-container mt-auto py-3">
     <div>
     </div>
   </footer>
</body>

</html>

web/templates/web/home.html
{% extends 'web/base.html' %}

{% block content %}

Initial

{% endblock %}